package entity

import "github.com/nbvghost/dandelion/entity/model"

var (
	User                 = (*model.User)(nil)
	UserInfo             = (*model.UserInfo)(nil)
	Admin                = (*model.Admin)(nil)
	Configuration        = (*model.Configuration)(nil)
	Logger               = (*model.Logger)(nil)
	UserJournal          = (*model.UserJournal)(nil)
	StoreJournal         = (*model.StoreJournal)(nil)
	CollageRecord        = (*model.CollageRecord)(nil)
	CollageGoods         = (*model.CollageGoods)(nil)
	District             = (*model.District)(nil)
	SupplyOrders         = (*model.SupplyOrders)(nil)
	StoreStock           = (*model.StoreStock)(nil)
	Verification         = (*model.Verification)(nil)
	FullCut              = (*model.FullCut)(nil)
	Voucher              = (*model.Voucher)(nil)
	TimeSell             = (*model.TimeSell)(nil)
	Store                = (*model.Store)(nil)
	ExpressTemplate      = (*model.ExpressTemplate)(nil)
	CardItem             = (*model.CardItem)(nil)
	Goods                = (*model.Goods)(nil)
	GoodsType            = (*model.GoodsType)(nil)
	GoodsTypeChild       = (*model.GoodsTypeChild)(nil)
	OrdersGoods          = (*model.OrdersGoods)(nil)
	ScoreJournal         = (*model.ScoreJournal)(nil)
	ScoreGoods           = (*model.ScoreGoods)(nil)
	Specification        = (*model.Specification)(nil)
	Transfers            = (*model.Transfers)(nil)
	Orders               = (*model.Orders)(nil)
	ShoppingCart         = (*model.ShoppingCart)(nil)
	Rank                 = (*model.Rank)(nil)
	GiveVoucher          = (*model.GiveVoucher)(nil)
	Organization         = (*model.Organization)(nil)
	OrganizationJournal  = (*model.OrganizationJournal)(nil)
	OrdersPackage        = (*model.OrdersPackage)(nil)
	Manager              = (*model.Manager)(nil)
	Collage              = (*model.Collage)(nil)
	Content              = (*model.Content)(nil)
	ContentItem          = (*model.ContentItem)(nil)
	ContentType          = (*model.ContentType)(nil)
	ContentSubType       = (*model.ContentSubType)(nil)
	Question             = (*model.Question)(nil)
	QuestionTag          = (*model.QuestionTag)(nil)
	AnswerQuestion       = (*model.AnswerQuestion)(nil)
	TimeSellGoods        = (*model.TimeSellGoods)(nil)
	ContentConfig        = (*model.ContentConfig)(nil)
	WXQRCodeParams       = (*model.WXQRCodeParams)(nil)
	GoodsAttributes      = (*model.GoodsAttributes)(nil)
	GoodsAttributesGroup = (*model.GoodsAttributesGroup)(nil)
	GoodsWish            = (*model.GoodsWish)(nil)
	LeaveMessage         = (*model.LeaveMessage)(nil)
	Subscribe            = (*model.Subscribe)(nil)
	FullTextSearch       = (*model.FullTextSearch)(nil)
	Pinyin               = (*model.Pinyin)(nil)
	Language             = (*model.Language)(nil)
	Translate            = (*model.Translate)(nil)
	DNS                  = (*model.DNS)(nil)
	Advert               = (*model.Advert)(nil)
	WechatConfig         = (*model.WechatConfig)(nil)
	PushData             = (*model.PushData)(nil)
)
