version: "3.9"
networks:
  gateway_network:
    external: true
services:
  
  dingzhong:
    image: "ghcr.io/nbvghost/yimeng-backend/server:latest"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      ETCD_ENDPOINTS: "172.31.249.250:23791,172.31.249.250:23792,172.31.249.250:23793"
    networks:
      - gateway_network
