version: "3.9"
networks:
  gateway_network:
    external: true
services:

  dandelion_admin:
    image: "ghcr.io/nbvghost/dandelion_admin/server:latest"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      ETCD_ENDPOINTS: "172.31.249.250:23791,172.31.249.250:23792,172.31.249.250:23793"
    networks:
      - gateway_network

  sso:
    image: "ghcr.io/nbvghost/sso/server:latest"
    depends_on:
      - "dandelion_admin"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      ETCD_ENDPOINTS: "172.31.249.250:23791,172.31.249.250:23792,172.31.249.250:23793"
    networks:
      - gateway_network

  oss:
    image: "ghcr.io/nbvghost/oss/server:latest"
    depends_on:
      - "dandelion_admin"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./assets:/app/assets
    environment:
      ETCD_ENDPOINTS: "172.31.249.250:23791,172.31.249.250:23792,172.31.249.250:23793"
    networks:
      - gateway_network

  dandelion_site:
    image: "ghcr.io/nbvghost/dandelion_site/server:latest"
    depends_on:
      - "dandelion_admin"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      ETCD_ENDPOINTS: "172.31.249.250:23791,172.31.249.250:23792,172.31.249.250:23793"
    networks:
      - gateway_network

  dandelion_gateway:
    image: "ghcr.io/nbvghost/dandelion_gateway/server:latest"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./cert-dir:/app/cert-dir
      - ./log:/app/log
    ports:
      - "80:80"
      - "443:443"
    environment:
      ETCD_ENDPOINTS: "172.31.249.250:23791,172.31.249.250:23792,172.31.249.250:23793"
    networks:
      - gateway_network